app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/fizzbuzzdb
    username: postgres
    password: whatever-565
    pool-szie: 30
spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
